---
regkey_pool: "wwt_lab_license_pool"
bigip_devices:
  F5_A:
    ip: '192.168.2.245'
    state: 'present'
    hostname: 'bigip-a.example.net'
    device_conflict_policy: "use_bigip"
    modules:
      - ltm
      - asm
      - security_shared
  F5_B:
    ip: '192.168.2.246'
    state: 'present'
    hostname: 'bigip-b.example.net'
    device_conflict_policy: "use_bigip"
  